config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/fun'
  get 'home/waste'
  get 'home/play'
  resources :messages
  resources :users
  # root to: 'application#hello'
  # root to: 'messages#index'
  root to: 'home#index'
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html:"Hello World"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def fun
  end

  def waste
  end

  def play
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:contet, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/fun.html.erb
<%= provide( :title, "/fun" ) %>
<div class="wrapper">
  <%= render 'layouts/aside' %>
  <div class="wrapper_main">
    <table class = "bingo">
      <thead>
        <tr><th>B</th><th>I</th><th>N</th><th>G</th><th>O</th></tr>
      </thead>
      <tbody>

        </tbody>

    </table>
  </div>
</div>

<script>
'use strict';

  {
    function createColumn(col) {
      const source = [];
      for (let i = 0; i < 15; i++) {
        source[i] = i + 1 + 15 * col;
      }

      const column = [];
      for (let i = 0; i < 5; i++) {
        column[i] = source.splice(Math.floor(Math.random() * source.length), 1)[0];
      }

      return column;
    }

    function createColumns() {
      const columns = [];
      for (let i = 0; i < 5; i++) {
        columns[i] = createColumn(i);
      }
      columns[2][2] = 'FREE';
      return columns;
    }

    function renderBingo(columns) {
      for (let row = 0; row < 5; row++) {
        const tr = document.createElement('tr');
        for (let col = 0; col < 5; col++) {
          const td = document.createElement('td');
          td.textContent = columns[col][row];
          tr.appendChild(td);
        }
        document.querySelector('tbody').appendChild(tr);
      }
    }

    const columns = createColumns();
    renderBingo(columns);
  }

</script>

app/views/home/index.html.erb
<%= provide( :title, " ") %>
<div class="wrapper">
  <%= render 'layouts/aside' %>
  <div class="wrapper_main">
    <div class="left-header" >
      <div class="left-header_title" >
          グループ名
      <ul class="left-header_members" >
          Member：
          <li class="left-header_member"> メンバー名 </li>
          <li class="left-header_member"> メンバー名 </li>
          <li class="left-header_member"> メンバー名 </li>
      </ul>
      </div>
    </div>

      <div class="right-header" >
        <div class="right-header_button" >
          <%= link_to "Edit", "#" %>
        </div>
      </div>
    <div class ="message">
      <div class="message-upper" >
        <div class="message-upper_user-name" >
            メンバー
        </div>
        <div class="message-upper_date" >
            2017/04/04
        </div>
        <div class="meesage-lower">
          <div class="message-lower_content">
            メッセージ
          </div>
        </div>
      </div>
     <div class="message-upper" >
        <div class="message-upper_user-name" >
            メンバー
        </div>
        <div class="message-upper_date" >
            2017/04/04
        </div>
        <div class="meesage-lower">
          <div class="message-lower_content">
            メッセージ
          </div>
        </div>
      </div>
      <div class="message-upper" >
        <div class="message-upper_user-name" >
            メンバー
        </div>
        <div class="message-upper_date" >
            2017/04/04
        </div>
        <div class="meesage-lower">
          <div class="message-lower_content">
            メッセージ
          </div>
        </div>
      </div>
    </div>

<div class="wrapper_main_form">

  <%= form_with(model: @micropost, local: true) do |f| %>
    <%# <%= render 'shared/error_messages', object: f.object%>

   <%= f.text_area :content, placeholder: "投稿してください。", class: "form_content" %>

   <%= f.submit "投稿する。", class: "form-btn" %>

   <span class="image">
    <%# <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
   </span>

  <% end %>

 </div>
  </div>
</div>

app/views/home/play.html.erb
<%= provide( :title, "/play" ) %>
<div class="wrapper">
  <%= render 'layouts/aside' %>
  <div class="wrapper_main">
    <div id="omikuji">?</div>
  </div>
</div>

<script>
'use strict';

{
  const btn = document.getElementById('omikuji');

  btn.addEventListener('click', () => {
    const n = Math.floor(Math.random() * 3);
    // btn.textContent = n;

    switch (n) {
      case 0:
        btn.textContent = '大吉';
        break;
      case 1:
        btn.textContent = '中吉';
        break;
      case 2:
        btn.textContent = '凶';
        break;
    }
  });
}
</script>

app/views/home/waste.html.erb
<%= provide( :title, "/waste" ) %>
<div class="wrapper">
  <%= render 'layouts/aside' %>
  <div class="wrapper_main">
   <table class="calender">
    <thead class="calender_title">
      <tr>
        <th id="prev">&laquo;</th>
        <th id="title" colspan="5">2020/05</th>
        <th id="next">&raquo;</th>
      </tr>
      <tr>
        <th>Sun</th>
        <th>Mon</th>
        <th>Tue</th>
        <th>Web</th>
        <th>Thu</th>
        <th>Fri</th>
        <th>Sat</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
        </tr>
        <tr>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
        </tr>
        <tr>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
        </tr>
        <tr>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
        </tr>
        <tr>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
        </tr>
    </tbody>
    <tfoot>
      <tr>
        <td id="today" colspan="7">Today</td>
      </tr>
    </tfoot>
   </table>
  </div>
</div>

<script>
  'use strict';

  {
    const year = 2020;
    const month = 4;
  }
</script>

app/views/layouts/_aside.html.erb
<div class="wrapper_aside">
  <div class ="wrapper_aside_top">
    <div class="side-bar">
      <div class="side-bar_name">
        Toyoji
      </div>
      <div class="side-bar_link">
      <%= link_to "#",class: "side-bar_icon"  do %>
        <i class="fas fa-cog"></i>
      <% end %>
      <%= link_to "#",class: "side-bar_icon"  do %>
        <i class="fas fa-edit"></i>
      <% end %>
      </div>
    </div>
  </div>
  <div class="wrapper_aside_middle">
    <div class="group">
      <div class="group_name">
      チャットグループ
      </div>
      <div class="group_message">
      まだ　メッセージはありません。
      </div>
    </div>
  </div>
  <div class="wrapper_aside_middle">
    <div class="group">
      <div class="group_name">
      チャットグループ
      </div>
      <div class="group_message">
      まだ　メッセージはありません。
      </div>
    </div>
  </div>
  <div class="wrapper_aside_middle">
    <div class="group">
      <div class="group_name">
      チャットグループ
      </div>
      <div class="group_message">
      まだ　メッセージはありません。
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer-nav">

  </div>
  <div class="footer-nav">
   <%=link_to "利用規約", "#" %>
  </div>
  <div class="footer-nav">
   <%= link_to "プライバシーポリシー", "#" %>
  </div>
  <div class="footer-nav">
   <%= link_to "お問合せ", "#" %>
  </div>
  <div class="footer-nav">

  </div>
</footer>

app/views/layouts/_header.html.erb
<header class ="header">
  <div class="header-left">
    <%= link_to image_tag("united-nations-303670_1280.png",alt:"logo", width:"80px", class:"header-left-logo"), root_url %>
    <h2 class="header-left-title"><%= link_to "CHAT APP", root_url, alt:"title", data: {"turbolinks" => false} %></h2>
  </div>
  <div class="header-middle">
    <div class="header-middle-center"></div>
    <div class="header-middle-link">
      <ul class="header-middle-link_path">
        <li><%= link_to "bingo_fun", home_fun_path, class:"#" %></li>
        <li><%= link_to "calendar＿waste", home_waste_path, class:"#" %></li>
        <li><%= link_to "omikuji_play", home_play_path, class:"#" %></li>
      </ul>
    </div>
  </div>
  <div class="header-right">
    <div class="header-button"><%= link_to "ログイン", "#" %></div>
    <div class="header-button"><%= link_to "新規登録", "#" %></div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatapp3<%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :contet %>
    <%= form.text_area :contet %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Contet</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.contet %></td>
        <td><%= message.user_id %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contet:</strong>
  <%= @message.contet %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user_id %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>